#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# One-time Google Cloud setup for Finnie's database-backed features
# (persistence, pgvector knowledge base, FAQ cache, memory):
#   Cloud SQL for PostgreSQL · DATABASE_URL secret · least-privilege runtime
#   service account · Cloud Build deploy permissions · first deploy.
#
# Idempotent: every stage checks what already exists, so re-running is safe.
# Non-secret choices are remembered in deploy/.gcp.env (git-ignored); the
# database password goes straight into Secret Manager and is never written
# to disk or printed.

ENV_FILE="${ENV_FILE:-deploy/.gcp.env}"
TOTAL_STAGES=7

# Is a resource there already? (Runs a describe; true if it succeeds.)
exists() { "$@" >/dev/null 2>&1; }

banner "Finnie · Google Cloud setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Project, region and APIs"
say "Confirm where Finnie runs. Defaults match the current deployment."
ask GCP_PROJECT   "GCP project id (current: finnie-agent):"; GCP_PROJECT="${GCP_PROJECT:-finnie-agent}"
ask GCP_REGION    "Region (current: us-central1):";          GCP_REGION="${GCP_REGION:-us-central1}"
ask RUN_SERVICE   "Cloud Run service (current: finnie-app):";  RUN_SERVICE="${RUN_SERVICE:-finnie-app}"
write_env GCP_PROJECT "$GCP_PROJECT"; write_env GCP_REGION "$GCP_REGION"; write_env RUN_SERVICE "$RUN_SERVICE"

gcloud auth print-access-token >/dev/null 2>&1 || { warn "Not signed in to gcloud."; step "Run: gcloud auth login   — then re-run this wizard."; exit 1; }
gcloud config set project "$GCP_PROJECT" >/dev/null
step "Enabling APIs (no-op if already on): Cloud SQL Admin, Secret Manager, Cloud Run, Cloud Build, Artifact Registry, IAM"
gcloud services enable sqladmin.googleapis.com secretmanager.googleapis.com run.googleapis.com \
  cloudbuild.googleapis.com artifactregistry.googleapis.com iam.googleapis.com
PROJECT_NUMBER=$(gcloud projects describe "$GCP_PROJECT" --format='value(projectNumber)')
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Runtime service account"
RUNTIME_SA="finnie-run@${GCP_PROJECT}.iam.gserviceaccount.com"
say "The service currently runs as the default compute service account, which"
say "usually holds Editor on the whole project. Finnie needs only to read its"
say "secrets, reach Cloud SQL, and write logs."
if exists gcloud iam service-accounts describe "$RUNTIME_SA"; then
  note "exists: $RUNTIME_SA"
else
  gcloud iam service-accounts create finnie-run --display-name="Finnie Cloud Run runtime"
fi
for role in roles/cloudsql.client roles/logging.logWriter; do
  gcloud projects add-iam-policy-binding "$GCP_PROJECT" --member="serviceAccount:$RUNTIME_SA" \
    --role="$role" --condition=None >/dev/null
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$role"
done
write_env RUNTIME_SA "$RUNTIME_SA"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloud SQL instance (PostgreSQL 16)"
ask SQL_INSTANCE "Instance name (default: finnie-db):"; SQL_INSTANCE="${SQL_INSTANCE:-finnie-db}"
write_env SQL_INSTANCE "$SQL_INSTANCE"
if exists gcloud sql instances describe "$SQL_INSTANCE"; then
  note "exists: $SQL_INSTANCE — skipping creation"
else
  say "Tier db-g1-small (shared core, 1.7 GB) is ample for Finnie's load; db-f1-micro"
  say "(0.6 GB) is cheaper but tight. Daily backups and deletion protection are on."
  open_url "https://cloud.google.com/sql/pricing#postgres-sql-pricing"
  ask SQL_TIER "Machine tier (default: db-g1-small):"; SQL_TIER="${SQL_TIER:-db-g1-small}"
  write_env SQL_TIER "$SQL_TIER"
  warn "This creates a billed resource and takes roughly 5–10 minutes."
  if confirm "Create Cloud SQL instance $SQL_INSTANCE ($SQL_TIER) in $GCP_REGION?"; then
    gcloud sql instances create "$SQL_INSTANCE" \
      --database-version=POSTGRES_16 --edition=ENTERPRISE --tier="$SQL_TIER" \
      --region="$GCP_REGION" --storage-auto-increase \
      --backup-start-time=03:00 --deletion-protection
  else
    warn "Skipped. Re-run the wizard when you're ready — later stages need the instance."
    exit 0
  fi
fi
SQL_CONNECTION=$(gcloud sql instances describe "$SQL_INSTANCE" --format='value(connectionName)')
write_env SQL_CONNECTION "$SQL_CONNECTION"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Database, user and the DATABASE_URL secret"
if exists gcloud sql databases describe finnie --instance="$SQL_INSTANCE"; then
  note "database 'finnie' exists"
else
  gcloud sql databases create finnie --instance="$SQL_INSTANCE"
fi
if exists gcloud secrets describe DATABASE_URL && ! confirm "DATABASE_URL already exists. Rotate the database password and replace it?"; then
  note "kept the existing DATABASE_URL"
else
  # Hex: URL-safe, so it needs no escaping inside the connection string.
  DB_PASSWORD=$(openssl rand -hex 24)
  if gcloud sql users list --instance="$SQL_INSTANCE" --format='value(name)' | grep -qx finnie; then
    gcloud sql users set-password finnie --instance="$SQL_INSTANCE" --password="$DB_PASSWORD"
  else
    gcloud sql users create finnie --instance="$SQL_INSTANCE" --password="$DB_PASSWORD"
  fi
  # Cloud Run mounts the instance's socket at /cloudsql/<connection name>.
  DATABASE_URL="postgresql://finnie:${DB_PASSWORD}@/finnie?host=/cloudsql/${SQL_CONNECTION}"
  if exists gcloud secrets describe DATABASE_URL; then
    printf '%s' "$DATABASE_URL" | gcloud secrets versions add DATABASE_URL --data-file=- >/dev/null
  else
    printf '%s' "$DATABASE_URL" | gcloud secrets create DATABASE_URL --data-file=- >/dev/null
  fi
  unset DB_PASSWORD DATABASE_URL
  printf '  %s✓%s DATABASE_URL stored in Secret Manager (password never shown or saved)\n' "$GREEN" "$RESET"
fi
note "Users created through Cloud SQL belong to cloudsqlsuperuser, which is what"
note "lets the app run CREATE EXTENSION vector on first start."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Secret access for the runtime service account"
say "The new service account must read every secret the service uses today,"
say "plus DATABASE_URL — or the next revision fails to start."
SERVICE_SECRETS=$(gcloud run services describe "$RUN_SERVICE" --region="$GCP_REGION" \
  --format=json 2>/dev/null | python3 -c '
import json, sys
try:
    spec = json.load(sys.stdin)["spec"]["template"]["spec"]["containers"][0]
except Exception:
    sys.exit(0)
for env in spec.get("env", []):
    ref = env.get("valueFrom", {}).get("secretKeyRef")
    if ref: print(ref["name"])
' | sort -u)
for secret in $SERVICE_SECRETS DATABASE_URL; do
  gcloud secrets add-iam-policy-binding "$secret" --member="serviceAccount:$RUNTIME_SA" \
    --role=roles/secretmanager.secretAccessor >/dev/null
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$secret"
done
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Cloud Build deploy permissions"
BUILD_SA=$(gcloud builds get-default-service-account --format='value(serviceAccountEmail)' | sed 's|.*/||')
say "Cloud Build runs as: $BUILD_SA"
say "It needs to deploy Cloud Run revisions that run as $RUNTIME_SA."
gcloud projects add-iam-policy-binding "$GCP_PROJECT" --member="serviceAccount:$BUILD_SA" \
  --role=roles/run.admin --condition=None >/dev/null
printf '  %s✓%s roles/run.admin\n' "$GREEN" "$RESET"
gcloud iam service-accounts add-iam-policy-binding "$RUNTIME_SA" \
  --member="serviceAccount:$BUILD_SA" --role=roles/iam.serviceAccountUser >/dev/null
printf '  %s✓%s roles/iam.serviceAccountUser on %s\n' "$GREEN" "$RESET" "$RUNTIME_SA"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Build and deploy"
SUBMIT="gcloud builds submit --config cloudbuild.yaml --substitutions=_REGION=$GCP_REGION,_SERVICE=$RUN_SERVICE,_RUNTIME_SA=$RUNTIME_SA,_CLOUDSQL_INSTANCE=$SQL_CONNECTION ."
say "Every future deploy is this one command (also saved as DEPLOY_COMMAND):"
note "$SUBMIT"
write_env DEPLOY_COMMAND "$SUBMIT"
say "Traffic only moves once the new revision starts and its migrations pass;"
say "if anything fails, the current revision keeps serving."
if confirm "Build and deploy now?"; then
  eval "$SUBMIT"
  step "Check the new revision's startup: look for 'database ready' and 'postgres_pool_open'."
  note "gcloud run services logs read $RUN_SERVICE --region=$GCP_REGION --limit=50"
else
  SKIPPED+=("first deploy: $SUBMIT")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
